name: use external docker repository

on: 
  push:
    branches:
      - main
      - develop

jobs: 
  builds_docker_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 外部のリポジトリのdocker imageを利用する。
      - uses: umi-yana/docker_python@main
        with:
          # コンテナ内でget-title.pyを実行する
          entrypoint: /bin/bash
          args: -c "python  ./.github/actions/external_repo/get-title.py"

          # この書き方でもOK
          # entrypoint: ./.github/actions/external_repo/action.sh



