name: next
on:
  workflow_run:
    workflows: [use external docker repository]
    types: [completed]
jobs:
  myjob:
    runs-on: ubuntu-latest
    # 前のWFが成功したら、下記stepsを実行する.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "hello world"
